---
linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - goimports
    - govet
    - ineffassign
    - misspell
    - unconvert

run:
  skip-dirs:
    - build

issues:
  # Enforce doc comments on exported types.
  include:
    - EXC0002
