// Code generated by protoc-gen-go. DO NOT EDIT.
// source: jasper.proto

package internal

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LogType int32

const (
	LogType_LOGUNKNOWN       LogType = 0
	LogType_LOGBUILDLOGGERV2 LogType = 1
	LogType_LOGBUILDLOGGERV3 LogType = 2
	LogType_LOGDEFAULT       LogType = 3
	LogType_LOGFILE          LogType = 4
	LogType_LOGINHERIT       LogType = 5
	LogType_LOGSPLUNK        LogType = 6
	LogType_LOGSUMOLOGIC     LogType = 7
	LogType_LOGINMEMORY      LogType = 8
)

var LogType_name = map[int32]string{
	0: "LOGUNKNOWN",
	1: "LOGBUILDLOGGERV2",
	2: "LOGBUILDLOGGERV3",
	3: "LOGDEFAULT",
	4: "LOGFILE",
	5: "LOGINHERIT",
	6: "LOGSPLUNK",
	7: "LOGSUMOLOGIC",
	8: "LOGINMEMORY",
}

var LogType_value = map[string]int32{
	"LOGUNKNOWN":       0,
	"LOGBUILDLOGGERV2": 1,
	"LOGBUILDLOGGERV3": 2,
	"LOGDEFAULT":       3,
	"LOGFILE":          4,
	"LOGINHERIT":       5,
	"LOGSPLUNK":        6,
	"LOGSUMOLOGIC":     7,
	"LOGINMEMORY":      8,
}

func (x LogType) String() string {
	return proto.EnumName(LogType_name, int32(x))
}

func (LogType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d30110796082ce8e, []int{0}
}

type FilterSpecifications int32

const (
	FilterSpecifications_ALL        FilterSpecifications = 0
	FilterSpecifications_RUNNING    FilterSpecifications = 1
	FilterSpecifications_TERMINATED FilterSpecifications = 2
	FilterSpecifications_FAILED     FilterSpecifications = 3
	FilterSpecifications_SUCCESSFUL FilterSpecifications = 4
)

var FilterSpecifications_name = map[int32]string{
	0: "ALL",
	1: "RUNNING",
	2: "TERMINATED",
	3: "FAILED",
	4: "SUCCESSFUL",
}

var FilterSpecifications_value = map[string]int32{
	"ALL":        0,
	"RUNNING":    1,
	"TERMINATED": 2,
	"FAILED":     3,
	"SUCCESSFUL": 4,
}

func (x FilterSpecifications) String() string {
	return proto.EnumName(FilterSpecifications_name, int32(x))
}

func (FilterSpecifications) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d30110796082ce8e, []int{1}
}

type Signals int32

const (
	Signals_UNKNOWN Signals = 0
	Signals_SIGTERM Signals = 1
	Signals_SIGKILL Signals = 2
	Signals_SIGHUP  Signals = 3
	Signals_SIGINT  Signals = 4
	Signals_SIGUSR1 Signals = 5
	Signals_SIGUSR2 Signals = 6
)

var Signals_name = map[int32]string{
	0: "UNKNOWN",
	1: "SIGTERM",
	2: "SIGKILL",
	3: "SIGHUP",
	4: "SIGINT",
	5: "SIGUSR1",
	6: "SIGUSR2",
}

var Signals_value = map[string]int32{
	"UNKNOWN": 0,
	"SIGTERM": 1,
	"SIGKILL": 2,
	"SIGHUP":  3,
	"SIGINT":  4,
	"SIGUSR1": 5,
	"SIGUSR2": 6,
}

func (x Signals) String() string {
	return proto.EnumName(Signals_name, int32(x))
}

func (Signals) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d30110796082ce8e, []int{2}
}

type Logger struct {
	LogType              LogType  `protobuf:"varint,1,opt,name=log_type,json=logType,proto3,enum=jasper.LogType" json:"log_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Logger) Reset()         { *m = Logger{} }
func (m *Logger) String() string { return proto.CompactTextString(m) }
func (*Logger) ProtoMessage()    {}
func (*Logger) Descriptor() ([]byte, []int) {
	return fileDescriptor_d30110796082ce8e, []int{0}
}
func (m *Logger) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Logger.Unmarshal(m, b)
}
func (m *Logger) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Logger.Marshal(b, m, deterministic)
}
func (m *Logger) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Logger.Merge(m, src)
}
func (m *Logger) XXX_Size() int {
	return xxx_messageInfo_Logger.Size(m)
}
func (m *Logger) XXX_DiscardUnknown() {
	xxx_messageInfo_Logger.DiscardUnknown(m)
}

var xxx_messageInfo_Logger proto.InternalMessageInfo

func (m *Logger) GetLogType() LogType {
	if m != nil {
		return m.LogType
	}
	return LogType_LOGUNKNOWN
}

type OutputOptions struct {
	Loggers               []*Logger `protobuf:"bytes,1,rep,name=loggers,proto3" json:"loggers,omitempty"`
	SuppressOutput        bool      `protobuf:"varint,2,opt,name=suppress_output,json=suppressOutput,proto3" json:"suppress_output,omitempty"`
	SuppressError         bool      `protobuf:"varint,3,opt,name=suppress_error,json=suppressError,proto3" json:"suppress_error,omitempty"`
	RedirectOutputToError bool      `protobuf:"varint,4,opt,name=redirect_output_to_error,json=redirectOutputToError,proto3" json:"redirect_output_to_error,omitempty"`
	RedirectErrorToOutput bool      `protobuf:"varint,5,opt,name=redirect_error_to_output,json=redirectErrorToOutput,proto3" json:"redirect_error_to_output,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}  `json:"-"`
	XXX_unrecognized      []byte    `json:"-"`
	XXX_sizecache         int32     `json:"-"`
}

func (m *OutputOptions) Reset()         { *m = OutputOptions{} }
func (m *OutputOptions) String() string { return proto.CompactTextString(m) }
func (*OutputOptions) ProtoMessage()    {}
func (*OutputOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_d30110796082ce8e, []int{1}
}
func (m *OutputOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutputOptions.Unmarshal(m, b)
}
func (m *OutputOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutputOptions.Marshal(b, m, deterministic)
}
func (m *OutputOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutputOptions.Merge(m, src)
}
func (m *OutputOptions) XXX_Size() int {
	return xxx_messageInfo_OutputOptions.Size(m)
}
func (m *OutputOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_OutputOptions.DiscardUnknown(m)
}

var xxx_messageInfo_OutputOptions proto.InternalMessageInfo

func (m *OutputOptions) GetLoggers() []*Logger {
	if m != nil {
		return m.Loggers
	}
	return nil
}

func (m *OutputOptions) GetSuppressOutput() bool {
	if m != nil {
		return m.SuppressOutput
	}
	return false
}

func (m *OutputOptions) GetSuppressError() bool {
	if m != nil {
		return m.SuppressError
	}
	return false
}

func (m *OutputOptions) GetRedirectOutputToError() bool {
	if m != nil {
		return m.RedirectOutputToError
	}
	return false
}

func (m *OutputOptions) GetRedirectErrorToOutput() bool {
	if m != nil {
		return m.RedirectErrorToOutput
	}
	return false
}

type CreateOptions struct {
	Args                 []string          `protobuf:"bytes,1,rep,name=args,proto3" json:"args,omitempty"`
	WorkingDirectory     string            `protobuf:"bytes,2,opt,name=working_directory,json=workingDirectory,proto3" json:"working_directory,omitempty"`
	Environment          map[string]string `protobuf:"bytes,3,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	OverrideEnviron      bool              `protobuf:"varint,4,opt,name=override_environ,json=overrideEnviron,proto3" json:"override_environ,omitempty"`
	TimeoutSeconds       int64             `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	Tags                 []string          `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	OnSuccess            []*CreateOptions  `protobuf:"bytes,7,rep,name=on_success,json=onSuccess,proto3" json:"on_success,omitempty"`
	OnFailure            []*CreateOptions  `protobuf:"bytes,8,rep,name=on_failure,json=onFailure,proto3" json:"on_failure,omitempty"`
	OnTimeout            []*CreateOptions  `protobuf:"bytes,9,rep,name=on_timeout,json=onTimeout,proto3" json:"on_timeout,omitempty"`
	Output               *OutputOptions    `protobuf:"bytes,10,opt,name=output,proto3" json:"output,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateOptions) Reset()         { *m = CreateOptions{} }
func (m *CreateOptions) String() string { return proto.CompactTextString(m) }
func (*CreateOptions) ProtoMessage()    {}
func (*CreateOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_d30110796082ce8e, []int{2}
}
func (m *CreateOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOptions.Unmarshal(m, b)
}
func (m *CreateOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOptions.Marshal(b, m, deterministic)
}
func (m *CreateOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOptions.Merge(m, src)
}
func (m *CreateOptions) XXX_Size() int {
	return xxx_messageInfo_CreateOptions.Size(m)
}
func (m *CreateOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOptions.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOptions proto.InternalMessageInfo

func (m *CreateOptions) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *CreateOptions) GetWorkingDirectory() string {
	if m != nil {
		return m.WorkingDirectory
	}
	return ""
}

func (m *CreateOptions) GetEnvironment() map[string]string {
	if m != nil {
		return m.Environment
	}
	return nil
}

func (m *CreateOptions) GetOverrideEnviron() bool {
	if m != nil {
		return m.OverrideEnviron
	}
	return false
}

func (m *CreateOptions) GetTimeoutSeconds() int64 {
	if m != nil {
		return m.TimeoutSeconds
	}
	return 0
}

func (m *CreateOptions) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *CreateOptions) GetOnSuccess() []*CreateOptions {
	if m != nil {
		return m.OnSuccess
	}
	return nil
}

func (m *CreateOptions) GetOnFailure() []*CreateOptions {
	if m != nil {
		return m.OnFailure
	}
	return nil
}

func (m *CreateOptions) GetOnTimeout() []*CreateOptions {
	if m != nil {
		return m.OnTimeout
	}
	return nil
}

func (m *CreateOptions) GetOutput() *OutputOptions {
	if m != nil {
		return m.Output
	}
	return nil
}

type ProcessInfo struct {
	Id                   string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Pid                  int64          `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	HostId               string         `protobuf:"bytes,3,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Running              bool           `protobuf:"varint,4,opt,name=running,proto3" json:"running,omitempty"`
	Successful           bool           `protobuf:"varint,5,opt,name=successful,proto3" json:"successful,omitempty"`
	Complete             bool           `protobuf:"varint,6,opt,name=complete,proto3" json:"complete,omitempty"`
	Timedout             bool           `protobuf:"varint,7,opt,name=timedout,proto3" json:"timedout,omitempty"`
	Options              *CreateOptions `protobuf:"bytes,8,opt,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ProcessInfo) Reset()         { *m = ProcessInfo{} }
func (m *ProcessInfo) String() string { return proto.CompactTextString(m) }
func (*ProcessInfo) ProtoMessage()    {}
func (*ProcessInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d30110796082ce8e, []int{3}
}
func (m *ProcessInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessInfo.Unmarshal(m, b)
}
func (m *ProcessInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessInfo.Marshal(b, m, deterministic)
}
func (m *ProcessInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessInfo.Merge(m, src)
}
func (m *ProcessInfo) XXX_Size() int {
	return xxx_messageInfo_ProcessInfo.Size(m)
}
func (m *ProcessInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessInfo proto.InternalMessageInfo

func (m *ProcessInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ProcessInfo) GetPid() int64 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *ProcessInfo) GetHostId() string {
	if m != nil {
		return m.HostId
	}
	return ""
}

func (m *ProcessInfo) GetRunning() bool {
	if m != nil {
		return m.Running
	}
	return false
}

func (m *ProcessInfo) GetSuccessful() bool {
	if m != nil {
		return m.Successful
	}
	return false
}

func (m *ProcessInfo) GetComplete() bool {
	if m != nil {
		return m.Complete
	}
	return false
}

func (m *ProcessInfo) GetTimedout() bool {
	if m != nil {
		return m.Timedout
	}
	return false
}

func (m *ProcessInfo) GetOptions() *CreateOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

type StatusResponse struct {
	HostId               string   `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Active               bool     `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusResponse) Reset()         { *m = StatusResponse{} }
func (m *StatusResponse) String() string { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()    {}
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d30110796082ce8e, []int{4}
}
func (m *StatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse.Unmarshal(m, b)
}
func (m *StatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse.Marshal(b, m, deterministic)
}
func (m *StatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse.Merge(m, src)
}
func (m *StatusResponse) XXX_Size() int {
	return xxx_messageInfo_StatusResponse.Size(m)
}
func (m *StatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse proto.InternalMessageInfo

func (m *StatusResponse) GetHostId() string {
	if m != nil {
		return m.HostId
	}
	return ""
}

func (m *StatusResponse) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

type Filter struct {
	Name                 FilterSpecifications `protobuf:"varint,1,opt,name=name,proto3,enum=jasper.FilterSpecifications" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Filter) Reset()         { *m = Filter{} }
func (m *Filter) String() string { return proto.CompactTextString(m) }
func (*Filter) ProtoMessage()    {}
func (*Filter) Descriptor() ([]byte, []int) {
	return fileDescriptor_d30110796082ce8e, []int{5}
}
func (m *Filter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Filter.Unmarshal(m, b)
}
func (m *Filter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Filter.Marshal(b, m, deterministic)
}
func (m *Filter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Filter.Merge(m, src)
}
func (m *Filter) XXX_Size() int {
	return xxx_messageInfo_Filter.Size(m)
}
func (m *Filter) XXX_DiscardUnknown() {
	xxx_messageInfo_Filter.DiscardUnknown(m)
}

var xxx_messageInfo_Filter proto.InternalMessageInfo

func (m *Filter) GetName() FilterSpecifications {
	if m != nil {
		return m.Name
	}
	return FilterSpecifications_ALL
}

type SignalProcess struct {
	ProcessID            *JasperProcessID `protobuf:"bytes,1,opt,name=ProcessID,proto3" json:"ProcessID,omitempty"`
	Signal               Signals          `protobuf:"varint,2,opt,name=signal,proto3,enum=jasper.Signals" json:"signal,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SignalProcess) Reset()         { *m = SignalProcess{} }
func (m *SignalProcess) String() string { return proto.CompactTextString(m) }
func (*SignalProcess) ProtoMessage()    {}
func (*SignalProcess) Descriptor() ([]byte, []int) {
	return fileDescriptor_d30110796082ce8e, []int{6}
}
func (m *SignalProcess) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignalProcess.Unmarshal(m, b)
}
func (m *SignalProcess) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignalProcess.Marshal(b, m, deterministic)
}
func (m *SignalProcess) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignalProcess.Merge(m, src)
}
func (m *SignalProcess) XXX_Size() int {
	return xxx_messageInfo_SignalProcess.Size(m)
}
func (m *SignalProcess) XXX_DiscardUnknown() {
	xxx_messageInfo_SignalProcess.DiscardUnknown(m)
}

var xxx_messageInfo_SignalProcess proto.InternalMessageInfo

func (m *SignalProcess) GetProcessID() *JasperProcessID {
	if m != nil {
		return m.ProcessID
	}
	return nil
}

func (m *SignalProcess) GetSignal() Signals {
	if m != nil {
		return m.Signal
	}
	return Signals_UNKNOWN
}

type TagName struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TagName) Reset()         { *m = TagName{} }
func (m *TagName) String() string { return proto.CompactTextString(m) }
func (*TagName) ProtoMessage()    {}
func (*TagName) Descriptor() ([]byte, []int) {
	return fileDescriptor_d30110796082ce8e, []int{7}
}
func (m *TagName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TagName.Unmarshal(m, b)
}
func (m *TagName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TagName.Marshal(b, m, deterministic)
}
func (m *TagName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TagName.Merge(m, src)
}
func (m *TagName) XXX_Size() int {
	return xxx_messageInfo_TagName.Size(m)
}
func (m *TagName) XXX_DiscardUnknown() {
	xxx_messageInfo_TagName.DiscardUnknown(m)
}

var xxx_messageInfo_TagName proto.InternalMessageInfo

func (m *TagName) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type ProcessTags struct {
	ProcessID            string   `protobuf:"bytes,1,opt,name=processID,proto3" json:"processID,omitempty"`
	Tags                 []string `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProcessTags) Reset()         { *m = ProcessTags{} }
func (m *ProcessTags) String() string { return proto.CompactTextString(m) }
func (*ProcessTags) ProtoMessage()    {}
func (*ProcessTags) Descriptor() ([]byte, []int) {
	return fileDescriptor_d30110796082ce8e, []int{8}
}
func (m *ProcessTags) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessTags.Unmarshal(m, b)
}
func (m *ProcessTags) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessTags.Marshal(b, m, deterministic)
}
func (m *ProcessTags) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessTags.Merge(m, src)
}
func (m *ProcessTags) XXX_Size() int {
	return xxx_messageInfo_ProcessTags.Size(m)
}
func (m *ProcessTags) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessTags.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessTags proto.InternalMessageInfo

func (m *ProcessTags) GetProcessID() string {
	if m != nil {
		return m.ProcessID
	}
	return ""
}

func (m *ProcessTags) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type JasperProcessID struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JasperProcessID) Reset()         { *m = JasperProcessID{} }
func (m *JasperProcessID) String() string { return proto.CompactTextString(m) }
func (*JasperProcessID) ProtoMessage()    {}
func (*JasperProcessID) Descriptor() ([]byte, []int) {
	return fileDescriptor_d30110796082ce8e, []int{9}
}
func (m *JasperProcessID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JasperProcessID.Unmarshal(m, b)
}
func (m *JasperProcessID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JasperProcessID.Marshal(b, m, deterministic)
}
func (m *JasperProcessID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JasperProcessID.Merge(m, src)
}
func (m *JasperProcessID) XXX_Size() int {
	return xxx_messageInfo_JasperProcessID.Size(m)
}
func (m *JasperProcessID) XXX_DiscardUnknown() {
	xxx_messageInfo_JasperProcessID.DiscardUnknown(m)
}

var xxx_messageInfo_JasperProcessID proto.InternalMessageInfo

func (m *JasperProcessID) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type OperationOutcome struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OperationOutcome) Reset()         { *m = OperationOutcome{} }
func (m *OperationOutcome) String() string { return proto.CompactTextString(m) }
func (*OperationOutcome) ProtoMessage()    {}
func (*OperationOutcome) Descriptor() ([]byte, []int) {
	return fileDescriptor_d30110796082ce8e, []int{10}
}
func (m *OperationOutcome) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OperationOutcome.Unmarshal(m, b)
}
func (m *OperationOutcome) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OperationOutcome.Marshal(b, m, deterministic)
}
func (m *OperationOutcome) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OperationOutcome.Merge(m, src)
}
func (m *OperationOutcome) XXX_Size() int {
	return xxx_messageInfo_OperationOutcome.Size(m)
}
func (m *OperationOutcome) XXX_DiscardUnknown() {
	xxx_messageInfo_OperationOutcome.DiscardUnknown(m)
}

var xxx_messageInfo_OperationOutcome proto.InternalMessageInfo

func (m *OperationOutcome) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *OperationOutcome) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type BuildOptions struct {
	Target               string   `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Arch                 string   `protobuf:"bytes,2,opt,name=arch,proto3" json:"arch,omitempty"`
	Edition              string   `protobuf:"bytes,3,opt,name=edition,proto3" json:"edition,omitempty"`
	Debug                bool     `protobuf:"varint,4,opt,name=debug,proto3" json:"debug,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildOptions) Reset()         { *m = BuildOptions{} }
func (m *BuildOptions) String() string { return proto.CompactTextString(m) }
func (*BuildOptions) ProtoMessage()    {}
func (*BuildOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_d30110796082ce8e, []int{11}
}
func (m *BuildOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildOptions.Unmarshal(m, b)
}
func (m *BuildOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildOptions.Marshal(b, m, deterministic)
}
func (m *BuildOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildOptions.Merge(m, src)
}
func (m *BuildOptions) XXX_Size() int {
	return xxx_messageInfo_BuildOptions.Size(m)
}
func (m *BuildOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildOptions.DiscardUnknown(m)
}

var xxx_messageInfo_BuildOptions proto.InternalMessageInfo

func (m *BuildOptions) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *BuildOptions) GetArch() string {
	if m != nil {
		return m.Arch
	}
	return ""
}

func (m *BuildOptions) GetEdition() string {
	if m != nil {
		return m.Edition
	}
	return ""
}

func (m *BuildOptions) GetDebug() bool {
	if m != nil {
		return m.Debug
	}
	return false
}

type MongoDBDownloadOptions struct {
	BuildOptions         *BuildOptions `protobuf:"bytes,1,opt,name=build_options,json=buildOptions,proto3" json:"build_options,omitempty"`
	Path                 string        `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Releases             []string      `protobuf:"bytes,3,rep,name=releases,proto3" json:"releases,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *MongoDBDownloadOptions) Reset()         { *m = MongoDBDownloadOptions{} }
func (m *MongoDBDownloadOptions) String() string { return proto.CompactTextString(m) }
func (*MongoDBDownloadOptions) ProtoMessage()    {}
func (*MongoDBDownloadOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_d30110796082ce8e, []int{12}
}
func (m *MongoDBDownloadOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MongoDBDownloadOptions.Unmarshal(m, b)
}
func (m *MongoDBDownloadOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MongoDBDownloadOptions.Marshal(b, m, deterministic)
}
func (m *MongoDBDownloadOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MongoDBDownloadOptions.Merge(m, src)
}
func (m *MongoDBDownloadOptions) XXX_Size() int {
	return xxx_messageInfo_MongoDBDownloadOptions.Size(m)
}
func (m *MongoDBDownloadOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_MongoDBDownloadOptions.DiscardUnknown(m)
}

var xxx_messageInfo_MongoDBDownloadOptions proto.InternalMessageInfo

func (m *MongoDBDownloadOptions) GetBuildOptions() *BuildOptions {
	if m != nil {
		return m.BuildOptions
	}
	return nil
}

func (m *MongoDBDownloadOptions) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *MongoDBDownloadOptions) GetReleases() []string {
	if m != nil {
		return m.Releases
	}
	return nil
}

type CacheOptions struct {
	Disabled             bool     `protobuf:"varint,1,opt,name=disabled,proto3" json:"disabled,omitempty"`
	PruneDelay           int64    `protobuf:"varint,2,opt,name=prune_delay,json=pruneDelay,proto3" json:"prune_delay,omitempty"`
	MaxSize              int64    `protobuf:"varint,3,opt,name=max_size,json=maxSize,proto3" json:"max_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CacheOptions) Reset()         { *m = CacheOptions{} }
func (m *CacheOptions) String() string { return proto.CompactTextString(m) }
func (*CacheOptions) ProtoMessage()    {}
func (*CacheOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_d30110796082ce8e, []int{13}
}
func (m *CacheOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CacheOptions.Unmarshal(m, b)
}
func (m *CacheOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CacheOptions.Marshal(b, m, deterministic)
}
func (m *CacheOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CacheOptions.Merge(m, src)
}
func (m *CacheOptions) XXX_Size() int {
	return xxx_messageInfo_CacheOptions.Size(m)
}
func (m *CacheOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_CacheOptions.DiscardUnknown(m)
}

var xxx_messageInfo_CacheOptions proto.InternalMessageInfo

func (m *CacheOptions) GetDisabled() bool {
	if m != nil {
		return m.Disabled
	}
	return false
}

func (m *CacheOptions) GetPruneDelay() int64 {
	if m != nil {
		return m.PruneDelay
	}
	return 0
}

func (m *CacheOptions) GetMaxSize() int64 {
	if m != nil {
		return m.MaxSize
	}
	return 0
}

type DownloadInfo struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadInfo) Reset()         { *m = DownloadInfo{} }
func (m *DownloadInfo) String() string { return proto.CompactTextString(m) }
func (*DownloadInfo) ProtoMessage()    {}
func (*DownloadInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d30110796082ce8e, []int{14}
}
func (m *DownloadInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadInfo.Unmarshal(m, b)
}
func (m *DownloadInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadInfo.Marshal(b, m, deterministic)
}
func (m *DownloadInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadInfo.Merge(m, src)
}
func (m *DownloadInfo) XXX_Size() int {
	return xxx_messageInfo_DownloadInfo.Size(m)
}
func (m *DownloadInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadInfo proto.InternalMessageInfo

func (m *DownloadInfo) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *DownloadInfo) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func init() {
	proto.RegisterType((*Logger)(nil), "jasper.Logger")
	proto.RegisterType((*OutputOptions)(nil), "jasper.OutputOptions")
	proto.RegisterType((*CreateOptions)(nil), "jasper.CreateOptions")
	proto.RegisterMapType((map[string]string)(nil), "jasper.CreateOptions.EnvironmentEntry")
	proto.RegisterType((*ProcessInfo)(nil), "jasper.ProcessInfo")
	proto.RegisterType((*StatusResponse)(nil), "jasper.StatusResponse")
	proto.RegisterType((*Filter)(nil), "jasper.Filter")
	proto.RegisterType((*SignalProcess)(nil), "jasper.SignalProcess")
	proto.RegisterType((*TagName)(nil), "jasper.TagName")
	proto.RegisterType((*ProcessTags)(nil), "jasper.ProcessTags")
	proto.RegisterType((*JasperProcessID)(nil), "jasper.JasperProcessID")
	proto.RegisterType((*OperationOutcome)(nil), "jasper.OperationOutcome")
	proto.RegisterType((*BuildOptions)(nil), "jasper.BuildOptions")
	proto.RegisterType((*MongoDBDownloadOptions)(nil), "jasper.MongoDBDownloadOptions")
	proto.RegisterType((*CacheOptions)(nil), "jasper.CacheOptions")
	proto.RegisterType((*DownloadInfo)(nil), "jasper.DownloadInfo")
	proto.RegisterEnum("jasper.LogType", LogType_name, LogType_value)
	proto.RegisterEnum("jasper.FilterSpecifications", FilterSpecifications_name, FilterSpecifications_value)
	proto.RegisterEnum("jasper.Signals", Signals_name, Signals_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// JasperProcessManagerClient is the client API for JasperProcessManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JasperProcessManagerClient interface {
	Status(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*StatusResponse, error)
	Create(ctx context.Context, in *CreateOptions, opts ...grpc.CallOption) (*ProcessInfo, error)
	List(ctx context.Context, in *Filter, opts ...grpc.CallOption) (JasperProcessManager_ListClient, error)
	Group(ctx context.Context, in *TagName, opts ...grpc.CallOption) (JasperProcessManager_GroupClient, error)
	Get(ctx context.Context, in *JasperProcessID, opts ...grpc.CallOption) (*ProcessInfo, error)
	Wait(ctx context.Context, in *JasperProcessID, opts ...grpc.CallOption) (*OperationOutcome, error)
	Signal(ctx context.Context, in *SignalProcess, opts ...grpc.CallOption) (*OperationOutcome, error)
	Close(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*OperationOutcome, error)
	TagProcess(ctx context.Context, in *ProcessTags, opts ...grpc.CallOption) (*OperationOutcome, error)
	ResetTags(ctx context.Context, in *JasperProcessID, opts ...grpc.CallOption) (*OperationOutcome, error)
	GetTags(ctx context.Context, in *JasperProcessID, opts ...grpc.CallOption) (*ProcessTags, error)
	DownloadFile(ctx context.Context, in *DownloadInfo, opts ...grpc.CallOption) (*OperationOutcome, error)
	DownloadFileAsync(ctx context.Context, in *DownloadInfo, opts ...grpc.CallOption) (*OperationOutcome, error)
	DownloadMongoDB(ctx context.Context, in *MongoDBDownloadOptions, opts ...grpc.CallOption) (*OperationOutcome, error)
	ConfigureCache(ctx context.Context, in *CacheOptions, opts ...grpc.CallOption) (*OperationOutcome, error)
}

type jasperProcessManagerClient struct {
	cc *grpc.ClientConn
}

func NewJasperProcessManagerClient(cc *grpc.ClientConn) JasperProcessManagerClient {
	return &jasperProcessManagerClient{cc}
}

func (c *jasperProcessManagerClient) Status(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/jasper.JasperProcessManager/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jasperProcessManagerClient) Create(ctx context.Context, in *CreateOptions, opts ...grpc.CallOption) (*ProcessInfo, error) {
	out := new(ProcessInfo)
	err := c.cc.Invoke(ctx, "/jasper.JasperProcessManager/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jasperProcessManagerClient) List(ctx context.Context, in *Filter, opts ...grpc.CallOption) (JasperProcessManager_ListClient, error) {
	stream, err := c.cc.NewStream(ctx, &_JasperProcessManager_serviceDesc.Streams[0], "/jasper.JasperProcessManager/List", opts...)
	if err != nil {
		return nil, err
	}
	x := &jasperProcessManagerListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type JasperProcessManager_ListClient interface {
	Recv() (*ProcessInfo, error)
	grpc.ClientStream
}

type jasperProcessManagerListClient struct {
	grpc.ClientStream
}

func (x *jasperProcessManagerListClient) Recv() (*ProcessInfo, error) {
	m := new(ProcessInfo)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *jasperProcessManagerClient) Group(ctx context.Context, in *TagName, opts ...grpc.CallOption) (JasperProcessManager_GroupClient, error) {
	stream, err := c.cc.NewStream(ctx, &_JasperProcessManager_serviceDesc.Streams[1], "/jasper.JasperProcessManager/Group", opts...)
	if err != nil {
		return nil, err
	}
	x := &jasperProcessManagerGroupClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type JasperProcessManager_GroupClient interface {
	Recv() (*ProcessInfo, error)
	grpc.ClientStream
}

type jasperProcessManagerGroupClient struct {
	grpc.ClientStream
}

func (x *jasperProcessManagerGroupClient) Recv() (*ProcessInfo, error) {
	m := new(ProcessInfo)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *jasperProcessManagerClient) Get(ctx context.Context, in *JasperProcessID, opts ...grpc.CallOption) (*ProcessInfo, error) {
	out := new(ProcessInfo)
	err := c.cc.Invoke(ctx, "/jasper.JasperProcessManager/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jasperProcessManagerClient) Wait(ctx context.Context, in *JasperProcessID, opts ...grpc.CallOption) (*OperationOutcome, error) {
	out := new(OperationOutcome)
	err := c.cc.Invoke(ctx, "/jasper.JasperProcessManager/Wait", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jasperProcessManagerClient) Signal(ctx context.Context, in *SignalProcess, opts ...grpc.CallOption) (*OperationOutcome, error) {
	out := new(OperationOutcome)
	err := c.cc.Invoke(ctx, "/jasper.JasperProcessManager/Signal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jasperProcessManagerClient) Close(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*OperationOutcome, error) {
	out := new(OperationOutcome)
	err := c.cc.Invoke(ctx, "/jasper.JasperProcessManager/Close", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jasperProcessManagerClient) TagProcess(ctx context.Context, in *ProcessTags, opts ...grpc.CallOption) (*OperationOutcome, error) {
	out := new(OperationOutcome)
	err := c.cc.Invoke(ctx, "/jasper.JasperProcessManager/TagProcess", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jasperProcessManagerClient) ResetTags(ctx context.Context, in *JasperProcessID, opts ...grpc.CallOption) (*OperationOutcome, error) {
	out := new(OperationOutcome)
	err := c.cc.Invoke(ctx, "/jasper.JasperProcessManager/ResetTags", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jasperProcessManagerClient) GetTags(ctx context.Context, in *JasperProcessID, opts ...grpc.CallOption) (*ProcessTags, error) {
	out := new(ProcessTags)
	err := c.cc.Invoke(ctx, "/jasper.JasperProcessManager/GetTags", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jasperProcessManagerClient) DownloadFile(ctx context.Context, in *DownloadInfo, opts ...grpc.CallOption) (*OperationOutcome, error) {
	out := new(OperationOutcome)
	err := c.cc.Invoke(ctx, "/jasper.JasperProcessManager/DownloadFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jasperProcessManagerClient) DownloadFileAsync(ctx context.Context, in *DownloadInfo, opts ...grpc.CallOption) (*OperationOutcome, error) {
	out := new(OperationOutcome)
	err := c.cc.Invoke(ctx, "/jasper.JasperProcessManager/DownloadFileAsync", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jasperProcessManagerClient) DownloadMongoDB(ctx context.Context, in *MongoDBDownloadOptions, opts ...grpc.CallOption) (*OperationOutcome, error) {
	out := new(OperationOutcome)
	err := c.cc.Invoke(ctx, "/jasper.JasperProcessManager/DownloadMongoDB", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jasperProcessManagerClient) ConfigureCache(ctx context.Context, in *CacheOptions, opts ...grpc.CallOption) (*OperationOutcome, error) {
	out := new(OperationOutcome)
	err := c.cc.Invoke(ctx, "/jasper.JasperProcessManager/ConfigureCache", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JasperProcessManagerServer is the server API for JasperProcessManager service.
type JasperProcessManagerServer interface {
	Status(context.Context, *empty.Empty) (*StatusResponse, error)
	Create(context.Context, *CreateOptions) (*ProcessInfo, error)
	List(*Filter, JasperProcessManager_ListServer) error
	Group(*TagName, JasperProcessManager_GroupServer) error
	Get(context.Context, *JasperProcessID) (*ProcessInfo, error)
	Wait(context.Context, *JasperProcessID) (*OperationOutcome, error)
	Signal(context.Context, *SignalProcess) (*OperationOutcome, error)
	Close(context.Context, *empty.Empty) (*OperationOutcome, error)
	TagProcess(context.Context, *ProcessTags) (*OperationOutcome, error)
	ResetTags(context.Context, *JasperProcessID) (*OperationOutcome, error)
	GetTags(context.Context, *JasperProcessID) (*ProcessTags, error)
	DownloadFile(context.Context, *DownloadInfo) (*OperationOutcome, error)
	DownloadFileAsync(context.Context, *DownloadInfo) (*OperationOutcome, error)
	DownloadMongoDB(context.Context, *MongoDBDownloadOptions) (*OperationOutcome, error)
	ConfigureCache(context.Context, *CacheOptions) (*OperationOutcome, error)
}

func RegisterJasperProcessManagerServer(s *grpc.Server, srv JasperProcessManagerServer) {
	s.RegisterService(&_JasperProcessManager_serviceDesc, srv)
}

func _JasperProcessManager_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JasperProcessManagerServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jasper.JasperProcessManager/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JasperProcessManagerServer).Status(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _JasperProcessManager_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JasperProcessManagerServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jasper.JasperProcessManager/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JasperProcessManagerServer).Create(ctx, req.(*CreateOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _JasperProcessManager_List_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Filter)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(JasperProcessManagerServer).List(m, &jasperProcessManagerListServer{stream})
}

type JasperProcessManager_ListServer interface {
	Send(*ProcessInfo) error
	grpc.ServerStream
}

type jasperProcessManagerListServer struct {
	grpc.ServerStream
}

func (x *jasperProcessManagerListServer) Send(m *ProcessInfo) error {
	return x.ServerStream.SendMsg(m)
}

func _JasperProcessManager_Group_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TagName)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(JasperProcessManagerServer).Group(m, &jasperProcessManagerGroupServer{stream})
}

type JasperProcessManager_GroupServer interface {
	Send(*ProcessInfo) error
	grpc.ServerStream
}

type jasperProcessManagerGroupServer struct {
	grpc.ServerStream
}

func (x *jasperProcessManagerGroupServer) Send(m *ProcessInfo) error {
	return x.ServerStream.SendMsg(m)
}

func _JasperProcessManager_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JasperProcessID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JasperProcessManagerServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jasper.JasperProcessManager/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JasperProcessManagerServer).Get(ctx, req.(*JasperProcessID))
	}
	return interceptor(ctx, in, info, handler)
}

func _JasperProcessManager_Wait_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JasperProcessID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JasperProcessManagerServer).Wait(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jasper.JasperProcessManager/Wait",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JasperProcessManagerServer).Wait(ctx, req.(*JasperProcessID))
	}
	return interceptor(ctx, in, info, handler)
}

func _JasperProcessManager_Signal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignalProcess)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JasperProcessManagerServer).Signal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jasper.JasperProcessManager/Signal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JasperProcessManagerServer).Signal(ctx, req.(*SignalProcess))
	}
	return interceptor(ctx, in, info, handler)
}

func _JasperProcessManager_Close_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JasperProcessManagerServer).Close(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jasper.JasperProcessManager/Close",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JasperProcessManagerServer).Close(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _JasperProcessManager_TagProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessTags)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JasperProcessManagerServer).TagProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jasper.JasperProcessManager/TagProcess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JasperProcessManagerServer).TagProcess(ctx, req.(*ProcessTags))
	}
	return interceptor(ctx, in, info, handler)
}

func _JasperProcessManager_ResetTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JasperProcessID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JasperProcessManagerServer).ResetTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jasper.JasperProcessManager/ResetTags",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JasperProcessManagerServer).ResetTags(ctx, req.(*JasperProcessID))
	}
	return interceptor(ctx, in, info, handler)
}

func _JasperProcessManager_GetTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JasperProcessID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JasperProcessManagerServer).GetTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jasper.JasperProcessManager/GetTags",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JasperProcessManagerServer).GetTags(ctx, req.(*JasperProcessID))
	}
	return interceptor(ctx, in, info, handler)
}

func _JasperProcessManager_DownloadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JasperProcessManagerServer).DownloadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jasper.JasperProcessManager/DownloadFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JasperProcessManagerServer).DownloadFile(ctx, req.(*DownloadInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _JasperProcessManager_DownloadFileAsync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JasperProcessManagerServer).DownloadFileAsync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jasper.JasperProcessManager/DownloadFileAsync",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JasperProcessManagerServer).DownloadFileAsync(ctx, req.(*DownloadInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _JasperProcessManager_DownloadMongoDB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MongoDBDownloadOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JasperProcessManagerServer).DownloadMongoDB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jasper.JasperProcessManager/DownloadMongoDB",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JasperProcessManagerServer).DownloadMongoDB(ctx, req.(*MongoDBDownloadOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _JasperProcessManager_ConfigureCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CacheOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JasperProcessManagerServer).ConfigureCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jasper.JasperProcessManager/ConfigureCache",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JasperProcessManagerServer).ConfigureCache(ctx, req.(*CacheOptions))
	}
	return interceptor(ctx, in, info, handler)
}

var _JasperProcessManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "jasper.JasperProcessManager",
	HandlerType: (*JasperProcessManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _JasperProcessManager_Status_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _JasperProcessManager_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _JasperProcessManager_Get_Handler,
		},
		{
			MethodName: "Wait",
			Handler:    _JasperProcessManager_Wait_Handler,
		},
		{
			MethodName: "Signal",
			Handler:    _JasperProcessManager_Signal_Handler,
		},
		{
			MethodName: "Close",
			Handler:    _JasperProcessManager_Close_Handler,
		},
		{
			MethodName: "TagProcess",
			Handler:    _JasperProcessManager_TagProcess_Handler,
		},
		{
			MethodName: "ResetTags",
			Handler:    _JasperProcessManager_ResetTags_Handler,
		},
		{
			MethodName: "GetTags",
			Handler:    _JasperProcessManager_GetTags_Handler,
		},
		{
			MethodName: "DownloadFile",
			Handler:    _JasperProcessManager_DownloadFile_Handler,
		},
		{
			MethodName: "DownloadFileAsync",
			Handler:    _JasperProcessManager_DownloadFileAsync_Handler,
		},
		{
			MethodName: "DownloadMongoDB",
			Handler:    _JasperProcessManager_DownloadMongoDB_Handler,
		},
		{
			MethodName: "ConfigureCache",
			Handler:    _JasperProcessManager_ConfigureCache_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "List",
			Handler:       _JasperProcessManager_List_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Group",
			Handler:       _JasperProcessManager_Group_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "jasper.proto",
}

func init() { proto.RegisterFile("jasper.proto", fileDescriptor_d30110796082ce8e) }

var fileDescriptor_d30110796082ce8e = []byte{
	// 1398 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xdb, 0x6e, 0xdb, 0x46,
	0x10, 0x0d, 0x2d, 0x99, 0x94, 0x46, 0xb6, 0xcc, 0x6c, 0x1d, 0x47, 0x75, 0x83, 0xc4, 0x10, 0xd0,
	0xc6, 0x75, 0x11, 0x3b, 0x75, 0x5c, 0xe4, 0x52, 0x20, 0x8d, 0x2d, 0xc9, 0x8a, 0x6a, 0x5a, 0x0a,
	0x28, 0xa9, 0x69, 0xfb, 0x22, 0xd0, 0xe2, 0x9a, 0x61, 0x42, 0x71, 0x89, 0xe5, 0xd2, 0x89, 0xf2,
	0xda, 0x4f, 0x28, 0xd0, 0x2f, 0xe8, 0xdf, 0xf5, 0x13, 0xfa, 0x52, 0xec, 0x4d, 0x17, 0x57, 0x76,
	0xd0, 0x3e, 0x69, 0xe7, 0x72, 0x66, 0x67, 0x66, 0x67, 0x8e, 0x08, 0x2b, 0x6f, 0xbd, 0x34, 0xc1,
	0x74, 0x37, 0xa1, 0x84, 0x11, 0x64, 0x4a, 0x69, 0xf3, 0x8b, 0x80, 0x90, 0x20, 0xc2, 0x7b, 0x42,
	0x7b, 0x96, 0x9d, 0xef, 0xe1, 0x51, 0xc2, 0xc6, 0xd2, 0xa9, 0x7a, 0x00, 0xa6, 0x43, 0x82, 0x00,
	0x53, 0xb4, 0x03, 0x85, 0x88, 0x04, 0x03, 0x36, 0x4e, 0x70, 0xc5, 0xd8, 0x32, 0xb6, 0xcb, 0xfb,
	0x6b, 0xbb, 0x2a, 0x9e, 0x43, 0x82, 0xde, 0x38, 0xc1, 0xae, 0x15, 0xc9, 0x43, 0xf5, 0x6f, 0x03,
	0x56, 0x3b, 0x19, 0x4b, 0x32, 0xd6, 0x49, 0x58, 0x48, 0xe2, 0x14, 0x6d, 0x03, 0x37, 0x06, 0x98,
	0xa6, 0x15, 0x63, 0x2b, 0xb7, 0x5d, 0xda, 0x2f, 0xcf, 0x80, 0x03, 0x4c, 0x5d, 0x6d, 0x46, 0xf7,
	0x61, 0x2d, 0xcd, 0x92, 0x84, 0xe2, 0x34, 0x1d, 0x10, 0x11, 0xa3, 0xb2, 0xb4, 0x65, 0x6c, 0x17,
	0xdc, 0xb2, 0x56, 0xcb, 0xc8, 0xe8, 0x4b, 0x98, 0x68, 0x06, 0x98, 0x52, 0x42, 0x2b, 0x39, 0xe1,
	0xb7, 0xaa, 0xb5, 0x0d, 0xae, 0x44, 0x8f, 0xa1, 0x42, 0xb1, 0x1f, 0x52, 0x3c, 0x64, 0x2a, 0xde,
	0x80, 0x11, 0x05, 0xc8, 0x0b, 0xc0, 0x2d, 0x6d, 0x97, 0x81, 0x7b, 0xe4, 0xdf, 0x40, 0xe1, 0xce,
	0x71, 0x2a, 0xa3, 0xe5, 0x79, 0xa0, 0x00, 0xf4, 0x88, 0xc4, 0x57, 0x7f, 0xcf, 0xc3, 0x6a, 0x8d,
	0x62, 0x8f, 0x61, 0x5d, 0x3d, 0x82, 0xbc, 0x47, 0x03, 0x59, 0x7a, 0xd1, 0x15, 0x67, 0xf4, 0x0d,
	0xdc, 0x7c, 0x4f, 0xe8, 0xbb, 0x30, 0x0e, 0x06, 0x32, 0x08, 0xa1, 0x63, 0x51, 0x69, 0xd1, 0xb5,
	0x95, 0xa1, 0xae, 0xf5, 0xe8, 0x25, 0x94, 0x70, 0x7c, 0x11, 0x52, 0x12, 0x8f, 0x70, 0xcc, 0x2a,
	0x39, 0xd1, 0xc2, 0xaf, 0x74, 0x0b, 0xe7, 0x2e, 0xdb, 0x6d, 0x4c, 0x1d, 0x1b, 0x31, 0xa3, 0x63,
	0x77, 0x16, 0x8a, 0xbe, 0x06, 0x9b, 0x5c, 0x60, 0x4a, 0x43, 0x1f, 0x0f, 0x94, 0x5e, 0xb5, 0x61,
	0x4d, 0xeb, 0x55, 0x00, 0xfe, 0x12, 0x2c, 0x1c, 0x61, 0x92, 0xb1, 0x41, 0x8a, 0x87, 0x24, 0xf6,
	0x53, 0x51, 0x77, 0xce, 0x2d, 0x2b, 0x75, 0x57, 0x6a, 0x79, 0x79, 0xcc, 0x0b, 0xd2, 0x8a, 0x29,
	0xcb, 0xe3, 0x67, 0x74, 0x00, 0x40, 0xe2, 0x41, 0x9a, 0x0d, 0x87, 0x38, 0x4d, 0x2b, 0x96, 0x48,
	0xf8, 0xd6, 0xc2, 0x84, 0xdd, 0x22, 0x89, 0xbb, 0xd2, 0x4f, 0xa1, 0xce, 0xbd, 0x30, 0xca, 0x28,
	0xae, 0x14, 0x3e, 0x81, 0x3a, 0x96, 0x7e, 0x0a, 0xa5, 0x92, 0xaa, 0x14, 0x3f, 0x81, 0xea, 0x49,
	0x3f, 0xf4, 0x00, 0x4c, 0xf5, 0x9a, 0xb0, 0x65, 0xcc, 0x22, 0xe6, 0x26, 0xd7, 0x55, 0x4e, 0x9b,
	0xcf, 0xc1, 0xbe, 0xdc, 0x59, 0x64, 0x43, 0xee, 0x1d, 0x1e, 0x8b, 0x75, 0x28, 0xba, 0xfc, 0x88,
	0xd6, 0x61, 0xf9, 0xc2, 0x8b, 0x32, 0xac, 0x5e, 0x52, 0x0a, 0xcf, 0x96, 0x9e, 0x18, 0xd5, 0xbf,
	0x0c, 0x28, 0xbd, 0xa2, 0x84, 0x97, 0xd9, 0x8a, 0xcf, 0x09, 0x2a, 0xc3, 0x52, 0xe8, 0x2b, 0xe8,
	0x52, 0xe8, 0xf3, 0x58, 0x49, 0xe8, 0x0b, 0x5c, 0xce, 0xe5, 0x47, 0x74, 0x1b, 0xac, 0x37, 0x24,
	0x65, 0x83, 0xd0, 0x17, 0x93, 0x5d, 0x74, 0x4d, 0x2e, 0xb6, 0x7c, 0x54, 0x01, 0x8b, 0x66, 0x71,
	0x1c, 0xc6, 0x81, 0x7a, 0x3a, 0x2d, 0xa2, 0xbb, 0x00, 0xaa, 0xe5, 0xe7, 0x59, 0xa4, 0xa6, 0x74,
	0x46, 0x83, 0x36, 0xa1, 0x30, 0x24, 0xa3, 0x24, 0xc2, 0x0c, 0x57, 0x4c, 0x61, 0x9d, 0xc8, 0xdc,
	0xc6, 0x5b, 0xe8, 0xf3, 0x1e, 0x5a, 0xd2, 0xa6, 0x65, 0xb4, 0x07, 0x16, 0x91, 0xfd, 0xa8, 0x14,
	0xe6, 0x9b, 0x35, 0xdf, 0x5e, 0xed, 0x55, 0x3d, 0x84, 0x72, 0x97, 0x79, 0x2c, 0x4b, 0x5d, 0x9c,
	0x26, 0x24, 0x4e, 0xf1, 0x6c, 0x35, 0xc6, 0x5c, 0x35, 0x1b, 0x60, 0x7a, 0x43, 0x16, 0x5e, 0x60,
	0xb5, 0xe7, 0x4a, 0xaa, 0x3e, 0x03, 0xf3, 0x38, 0x8c, 0x18, 0xa6, 0xe8, 0x21, 0xe4, 0x63, 0x6f,
	0xa4, 0x69, 0xe7, 0x8e, 0xbe, 0x5a, 0x5a, 0xbb, 0x09, 0x1e, 0x86, 0xe7, 0xe1, 0xd0, 0x93, 0x19,
	0x08, 0xcf, 0x2a, 0x81, 0xd5, 0x6e, 0x18, 0xc4, 0x5e, 0xa4, 0x3a, 0x8e, 0xbe, 0x83, 0xa2, 0x6e,
	0x7e, 0x5d, 0xc4, 0x29, 0xed, 0xdf, 0xd6, 0x71, 0x7e, 0x14, 0x3f, 0x13, 0xb3, 0x3b, 0xf5, 0x44,
	0xf7, 0xc1, 0x4c, 0x45, 0x1c, 0x91, 0xdb, 0x0c, 0xe5, 0xc9, 0xe8, 0xa9, 0xab, 0xcc, 0xd5, 0x7b,
	0x60, 0xf5, 0xbc, 0xa0, 0xed, 0x8d, 0xf0, 0x74, 0x04, 0x8c, 0x99, 0x11, 0xa8, 0xfe, 0x30, 0x79,
	0xfd, 0x1e, 0x5f, 0x8f, 0x3b, 0x50, 0x4c, 0xe6, 0xf2, 0x29, 0xba, 0x53, 0xc5, 0x64, 0xa1, 0x96,
	0xa6, 0x0b, 0x55, 0xbd, 0x0f, 0x6b, 0x97, 0x12, 0xbd, 0xe2, 0xa6, 0x17, 0x60, 0x77, 0x12, 0x4c,
	0x45, 0x3f, 0x3a, 0x19, 0x1b, 0x92, 0x11, 0xe6, 0x13, 0xa3, 0x57, 0xd1, 0x90, 0x13, 0xa3, 0x44,
	0x71, 0x15, 0xfe, 0xc0, 0xd4, 0xbc, 0x8a, 0x73, 0xf5, 0x2d, 0xac, 0x1c, 0x65, 0x61, 0xe4, 0x6b,
	0xfa, 0xda, 0x00, 0x93, 0x79, 0x34, 0xc0, 0x4c, 0xbf, 0x9c, 0x94, 0x24, 0xad, 0x0d, 0xdf, 0x68,
	0x2c, 0x3f, 0xf3, 0x9b, 0xb0, 0x1f, 0x72, 0x9c, 0x1a, 0x5a, 0x2d, 0xf2, 0x6c, 0x7d, 0x7c, 0x96,
	0xe9, 0x99, 0x95, 0x42, 0xf5, 0x37, 0x03, 0x36, 0x4e, 0x49, 0x1c, 0x90, 0xfa, 0x51, 0x9d, 0xbc,
	0x8f, 0x23, 0xe2, 0x4d, 0xae, 0x7d, 0x0a, 0xab, 0x67, 0x3c, 0x8d, 0x81, 0x1e, 0x3d, 0xf9, 0x6e,
	0xeb, 0xfa, 0x0d, 0x66, 0x73, 0x74, 0x57, 0xce, 0x66, 0x33, 0x46, 0x90, 0x4f, 0x3c, 0x36, 0xc9,
	0x8c, 0x9f, 0xf9, 0x7c, 0x53, 0x1c, 0x61, 0x2f, 0xc5, 0xa9, 0x20, 0xd0, 0xa2, 0x3b, 0x91, 0xab,
	0xe7, 0xb0, 0x52, 0xf3, 0x86, 0x6f, 0x26, 0x84, 0xbd, 0x09, 0x05, 0x3f, 0x4c, 0xbd, 0xb3, 0x08,
	0xfb, 0xaa, 0x61, 0x13, 0x19, 0xdd, 0x83, 0x52, 0x42, 0xb3, 0x18, 0x0f, 0x7c, 0x1c, 0x79, 0x63,
	0xb5, 0xb0, 0x20, 0x54, 0x75, 0xae, 0x41, 0x9f, 0x43, 0x61, 0xe4, 0x7d, 0x18, 0xa4, 0xe1, 0x47,
	0x2c, 0x7a, 0x90, 0x73, 0xad, 0x91, 0xf7, 0xa1, 0x1b, 0x7e, 0xc4, 0xd5, 0x03, 0x58, 0xd1, 0x55,
	0x0a, 0x12, 0xb0, 0x21, 0x97, 0xd1, 0x48, 0x13, 0x48, 0x46, 0xa3, 0x45, 0x99, 0xef, 0xfc, 0x69,
	0x80, 0xa5, 0xfe, 0x63, 0x51, 0x19, 0xc0, 0xe9, 0x34, 0xfb, 0xed, 0x93, 0x76, 0xe7, 0x75, 0xdb,
	0xbe, 0x81, 0xd6, 0xc1, 0x76, 0x3a, 0xcd, 0xa3, 0x7e, 0xcb, 0xa9, 0x3b, 0x9d, 0x66, 0xb3, 0xe1,
	0xfe, 0xb4, 0x6f, 0x1b, 0x0b, 0xb4, 0x8f, 0xec, 0x25, 0x85, 0xad, 0x37, 0x8e, 0x0f, 0xfb, 0x4e,
	0xcf, 0xce, 0xa1, 0x12, 0x58, 0x4e, 0xa7, 0x79, 0xdc, 0x72, 0x1a, 0x76, 0x5e, 0x19, 0x5b, 0xed,
	0x97, 0x0d, 0xb7, 0xd5, 0xb3, 0x97, 0xd1, 0x2a, 0x14, 0x9d, 0x4e, 0xb3, 0xfb, 0xca, 0xe9, 0xb7,
	0x4f, 0x6c, 0x13, 0xd9, 0xb0, 0xc2, 0xc5, 0xfe, 0x69, 0x87, 0x7b, 0xd5, 0x6c, 0x0b, 0xad, 0x41,
	0x49, 0x00, 0x4e, 0x1b, 0xa7, 0x1d, 0xf7, 0x17, 0xbb, 0xb0, 0xf3, 0x33, 0xac, 0x2f, 0x5a, 0x49,
	0x64, 0x41, 0xee, 0xd0, 0x71, 0xec, 0x1b, 0xfc, 0x3e, 0xb7, 0xdf, 0x6e, 0xb7, 0xda, 0x4d, 0xdb,
	0xe0, 0xf7, 0xf5, 0x1a, 0xee, 0x69, 0xab, 0x7d, 0xd8, 0x6b, 0xd4, 0xed, 0x25, 0x04, 0x60, 0x1e,
	0x1f, 0xb6, 0x9c, 0x46, 0xdd, 0xce, 0x71, 0x5b, 0xb7, 0x5f, 0xab, 0x35, 0xba, 0xdd, 0xe3, 0xbe,
	0x63, 0xe7, 0x77, 0xce, 0xc0, 0x52, 0x0b, 0xc7, 0x63, 0x4c, 0x8b, 0x2f, 0x81, 0xd5, 0x6d, 0x35,
	0x79, 0x18, 0xdb, 0x50, 0xc2, 0x49, 0xcb, 0x71, 0x64, 0xb4, 0x6e, 0xab, 0xf9, 0xb2, 0xff, 0xca,
	0xce, 0xa9, 0x73, 0xab, 0xdd, 0xb3, 0xf3, 0xca, 0xa9, 0xdf, 0x75, 0xbf, 0xb5, 0x97, 0xa7, 0xc2,
	0xbe, 0x6d, 0xee, 0xff, 0x61, 0xc1, 0xfa, 0xdc, 0x82, 0x9d, 0x7a, 0xb1, 0xc7, 0x3f, 0x7c, 0x9e,
	0x80, 0x29, 0xa9, 0x0c, 0x6d, 0xec, 0xca, 0x4f, 0xa5, 0x5d, 0xfd, 0xa9, 0xb4, 0xdb, 0xe0, 0x9f,
	0x4a, 0x9b, 0x1b, 0x13, 0x56, 0x98, 0xa7, 0xbc, 0x03, 0x30, 0x25, 0x3d, 0xa2, 0xc5, 0x74, 0xb9,
	0xf9, 0x99, 0x56, 0xcf, 0xfe, 0x31, 0x3c, 0x80, 0xbc, 0x13, 0xa6, 0x0c, 0x95, 0xe7, 0x79, 0x6e,
	0xa1, 0xf3, 0x43, 0x03, 0xed, 0xc1, 0x72, 0x93, 0x92, 0x2c, 0x41, 0x13, 0x6e, 0x52, 0x44, 0x74,
	0x15, 0xe0, 0x11, 0xe4, 0x9a, 0x98, 0xa1, 0xab, 0xe8, 0x6f, 0x71, 0x52, 0x4f, 0x21, 0xff, 0xda,
	0x0b, 0xaf, 0x41, 0x55, 0x26, 0xff, 0x9e, 0x97, 0xb9, 0xe7, 0x29, 0x98, 0xf2, 0xf1, 0xa6, 0x5d,
	0x98, 0xe3, 0xe6, 0x6b, 0xa1, 0xcb, 0xb5, 0x88, 0xa4, 0xf8, 0xca, 0xce, 0x5f, 0x0d, 0xfd, 0x1e,
	0xa0, 0xe7, 0x05, 0x9a, 0xfe, 0x2f, 0xd7, 0xc4, 0x39, 0xf8, 0x1a, 0xf0, 0x73, 0x28, 0xba, 0x38,
	0xc5, 0x4c, 0x50, 0xf5, 0xff, 0x28, 0xf9, 0x31, 0x58, 0xcd, 0x4f, 0xa1, 0x17, 0xa5, 0x84, 0x9e,
	0x4f, 0xf9, 0xe1, 0x38, 0x8c, 0x30, 0x9a, 0x70, 0xdd, 0x2c, 0x6b, 0x5c, 0x73, 0x71, 0x0d, 0x6e,
	0xce, 0xe2, 0x0f, 0xd3, 0x71, 0x3c, 0xfc, 0xcf, 0x41, 0x4e, 0x60, 0x4d, 0x7b, 0x2a, 0x66, 0x46,
	0x77, 0xb5, 0xf3, 0x62, 0xaa, 0xbe, 0x26, 0xd8, 0x0b, 0x28, 0xd7, 0x48, 0x7c, 0x1e, 0x06, 0x19,
	0xc5, 0x82, 0x62, 0xa7, 0xe9, 0xcc, 0x32, 0xee, 0xd5, 0x11, 0x8e, 0xe0, 0xd7, 0x42, 0x18, 0x33,
	0x4c, 0x63, 0x2f, 0x3a, 0x33, 0xc5, 0xfb, 0x3f, 0xfa, 0x27, 0x00, 0x00, 0xff, 0xff, 0x04, 0x4b,
	0xde, 0xa9, 0xca, 0x0c, 0x00, 0x00,
}
